service: esg-app-planning-poker

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${env:STACK_ENV, 'dev'}
  # This role is required to deploy an application to AWS with an ESG Account. See https://wiki.york.ac.uk/display/AWS/AWS%3A+Github+Actions for details
#  cfnRole: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/GithubActionsDeploymentRole
  region: eu-west-1
  memorySize: 1024
  endpointType: regional
  environment:
    NODE_ENV: production
  stackTags:
    name: planning poker
    group: ESG
    status: dev
    pushed_by: github
    defined_in: serverless
    repo_name: esg-app-planning-poker
    team: ESG Teaching and Learning
  apiGateway:
    minimumCompressionSize: 1000
  iam:
    role:
      name: planning-poker-role-${self:provider.stage}
      statements:
        - Effect: Allow
          Resource: !GetAtt PokerTable.Arn
          Action: dynamodb:Scan
        - Effect: Allow
          Resource: !GetAtt PokerTable.Arn
          Action: dynamodb:GetItem
        - Effect: Allow
          Resource: !GetAtt PokerTable.Arn
          Action: dynamodb:PutItem
        - Effect: Allow
          Resource: !GetAtt PokerTable.Arn
          Action: dynamodb:UpdateItem

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}
  getRoom:
    handler: index.getRoom
    environment:
      POKER_TABLE: planning-poker-${self:provider.stage}
    events:
      - http:
          path: /room/{id}
          method: GET
          cors:
            origin: "*"
  createRoom:
    handler: index.createRoom
    environment:
      POKER_TABLE: planning-poker-${self:provider.stage}
    events:
      - http:
          path: /room
          method: POST
          cors:
            origin: "*"
  joinRoom:
    handler: index.joinRoom
    environment:
      POKER_TABLE: planning-poker-${self:provider.stage}
    events:
      - http:
          path: /room/{id}/join
          method: POST
          cors:
            origin: "*"
  submitChoice:
    handler: index.submitChoice
    environment:
      POKER_TABLE: planning-poker-${self:provider.stage}
    events:
      - http:
          path: /room/{id}/choice
          method: PUT
          cors:
            origin: "*"
  revealRoom:
    handler: index.revealRoom
    environment:
      POKER_TABLE: planning-poker-${self:provider.stage}
    events:
      - http:
          path: /room/{id}/reveal
          method: POST
          cors:
            origin: "*"
  resetRoom:
    handler: index.resetRoom
    environment:
      POKER_TABLE: planning-poker-${self:provider.stage}
    events:
      - http:
          path: /room/{id}/reset
          method: POST
          cors:
            origin: "*"

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - "*/*"
  domainName: ${env:DOMAIN_NAME, ''}
  sslCertificateArn: ${env:SSL_CERTIFICATE_ARN, ''}

# Exclude files and next.js dependencies that are not needed at runtime
package:
  include:
    - .env
    - .env.local
    - node_modules/@babel/runtime/**
  exclude:
    - .*
    - .gradle/**
    - .github/**
    - .idea/**
    - docs/**
    - src/**
    - package.json
    - package-lock.json
    - README.md
    - tsconfig.tsbuildinfo
    - tsconfig.json
    - .next/cache/webpack/client-development/**
    - .next/cache/webpack/client-development-fallback/**
    - .next/cache/webpack/server-development/**
    - node_modules/smartify-lib/node_modules/**
    - node_modules/@babel/**
    - node_modules/ally.js/**
    - node_modules/caniuse-lite/**
    - node_modules/lodash/**
    - node_modules/webpack/**
    - node_modules/terser/**
    - node_modules/es5-ext/**
    - node_modules/resolve-url-loader/**
    - node_modules/postcss/**
    - node_modules/acorn/**
    - node_modules/ajv/**
    - node_modules/@webassemblyjs/**
    - node_modules/cssnano-preset-simple/**
    - node_modules/snapdragon/**
    - node_modules/regenerate-unicode-properties/**
    - node_modules/pako/**
    - node_modules/source-map/**
    - node_modules/bluebird/**
    - node_modules/uri-js/**
    - node_modules/ast-types/**
    - node_modules/watchpack-chokidar2/**
    - node_modules/terser-webpack-plugin/**
    - node_modules/core-js-compat/**
    - node_modules/neo-async/**
    - node_modules/postcss-selector-parser/**
    - node_modules/css-loader/**
    - node_modules/sass-loader/**
    - node_modules/buffer/**
    - node_modules/adjust-sourcemap-loader/**
    - node_modules/ext/**
    - node_modules/tr46/**
    - node_modules/micromatch/**
    - node_modules/@ampproject/**
    - node_modules/postcss-modules-parser/**
    - node_modules/css-modules-loader-core/**
    - node_modules/babel-plugin-react-css-modules/**
    - node_modules/es-abstract/**
    - node_modules/string.prototype.trimstart/**
    - node_modules/string.prototype.trimend/**
    - node_modules/**/CHANGELOG*
    - node_modules/**/README*
    - node_modules/*/test/**
    - node_modules/**/.github/**
    - node_modules/@opentelemetry/**
    - node_modules/encoding/**
    - node_modules/@next/swc-android-arm64/**
    - node_modules/@next/swc-darwin-arm64/**
    - node_modules/@next/swc-darwin-x64/**
    - node_modules/@next/swc-linux-arm64-gnu/**
    - node_modules/@next/swc-linux-arm64-musl/**
    - node_modules/@next/swc-linux-arm-gnueabihf/**
    - node_modules/@next/swc-linux-x64-gnu/**
    - node_modules/@next/swc-linux-x64-musl/**
    - node_modules/@next/swc-win32-arm64-msvc/**
    - node_modules/@next/swc-win32-x64-msvc/**
    - node_modules/@next/swc-win32-ia32-msvc/**
    - node_modules/next/dist/compiled/babel/**
    - node_modules/next/dist/compiled/babel-packages/**

resources:
  Conditions:
    UseCustomDomainName: !Not
      - !Equals
        - ${self:custom.domainName}
        - ""

  Resources:
    PokerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: planning-poker-${self:provider.stage}
        BillingMode: PROVISIONED
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
