name: dev deployment

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install application dependencies
        run: npm ci

      - name: Install cypress system dependencies
        run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Check code is formatted correctly
        run: npm run checkformat

      - name: Check code conforms to linting rules
        run: npm run lint

      - name: Check tests run
        run: npm run test

      - name: Deploy - dev
        if: github.ref == 'refs/heads/dev'
        run: npm run deploy:dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          SSL_CERTIFICATE_ARN: ${{ secrets.DEV_SSL_CERTIFICATE_ARN }}
          DOMAIN_NAME: planning-poker.dev.app.york.ac.uk

  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: deploy
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install application dependencies
        run: npm ci

      - name: Install cypress system dependencies
        run: sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Verify development deployment
        run: npm run verify:dev

  performance-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: deploy
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Check Lighthouse performance score for development environment
        uses: university-of-york/esg-action-performance-check@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          iterations: 5
          minimum-desktop-score: 80
          minimum-mobile-score: 60
          urls: |
            https://planning-poker.dev.app.york.ac.uk/
            https://planning-poker.dev.app.york.ac.uk/table/6a9105cc-4671-4eab-a884-7f763a5411cf
