name: format

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install application dependencies
        run: npm ci

      - name: Check code is formatted correctly
        run: npm run checkformat
