name: package

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install application dependencies
        run: npm ci

      - name: Package application with serverless
        run: npm run package:dev
        env:
          AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          SSL_CERTIFICATE_ARN: ${{ secrets.DEV_SSL_CERTIFICATE_ARN }}
          DOMAIN_NAME: planning-poker.dev.app.york.ac.uk
