name: package

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install application dependencies
        run: npm ci

      - name: Package application with serverless
        run: npm run package
        env:
          STACK_ENV: dev
          AWS_ACCOUNT_ID: 1234567890

      - name: Store packaged application as artifact
        uses: actions/upload-artifact@v3
        with:
          name: serverless
          path: .serverless/
          retention-days: 14
